# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Kwiki-RecentChanges-Atom
version:      0.03
version_from: lib/Kwiki/RecentChanges/Atom.pm
installdirs:  site
requires:
    Kwiki:                         0
    Test::More:                    0
    XML::Atom::Entry:              0
    XML::Atom::Feed:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
